### ISSUE TITLE
When I try to run the ProjectX.py file I am getting errors

### ISSUE THREAD

**Issue by markojerry** [naaax123/Python-CSGO-Cheat#14]
When I try to run it with ```python3 ProjectX.py``` it gives me the following error:

```
Traceback (most recent call last):
  File "ProjectX.py", line 6, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
```
and when I try to run it with ```python ProjectX.py``` it gives me this different error:
```
  File "ProjectX.py", line 47
SyntaxError: Non-ASCII character '\xc2' in file ProjectX.py on line 47, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Any help on how I can fix this?
(I have installed everything in the requirements.txt file with ```pip install -r requirements.txt```)

**Comment by naaax123** [comment]
Change the variable antivac in line 47 to any string. Then run it with python ProjectX.py. The first error can be fixed by doing "python3 -m pip install -r requirements.txt". You have a diffrent python versions installed and thus different packet managers.

**Comment by markojerry** [comment]
> Change the variable antivac in line 47 to any string. Then run it with python ProjectX.py. The first error can be fixed by doing "python3 -m pip install -r requirements.txt". You have a diffrent python versions installed and thus different packet managers.

Hi, Thanks for your reply.
I changed the antivac variable to a random string and executed ```python3 -m pip install -r requirements.txt```.
Now when I try to do ```python ProjectX.py``` it says that the module ```keyboard``` is missing.
and trying to do ```pip install keyboard``` gives the output ```Requirement already satisfied```
Any help on this issue?

**Comment by naaax123** [comment]
try "python -m pip install keyboard"

**Comment by markojerry** [comment]
> try "python -m pip install keyboard"

It gave me the following output:
```C:\Users\Marko\.windows-build-tools\python27\python.exe: No module named pip```
Weird

**Comment by naaax123** [comment]
maybe run the cheat with "python3 ProjectX.py"

**Comment by markojerry** [comment]
> maybe run the cheat with "python3 ProjectX.py"

Welp, that error again
```Traceback (most recent call last):
  File "ProjectX.py", line 6, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed:
```

**Comment by markojerry** [comment]
And with ```python ProjectX.py```
```Traceback (most recent call last):
  File "ProjectX.py", line 3, in <module>
    import keyboard
ImportError: No module named keyboard
```

**Comment by naaax123** [comment]
are u using anaconda ?

**Comment by naaax123** [comment]
it seems like you didnt install python3 from the official python page
so python3.dll isnt installed and thus you cant use pyqt5
your other python installation doesnt seem to have pip installed

**Comment by markojerry** [comment]
> anaconda

I am not using anaconda.



> it seems like you didnt install python3 from the official python page
> so python3.dll isnt installed and thus you cant use pyqt5
> your other python installation doesnt seem to have pip installed

One Python install of mine is from the Microsoft Store (Python 3.7)
and the other Python Installation of which I do not know the version got automatically installed from the npm package ```windows-build-tools```
I will attempt to install Python 3.7 from the official Python website now and then give an update

**Comment by naaax123** [comment]
Nice, make sure to add it to path, to install pip and to remove the other installations

**Comment by markojerry** [comment]
Everything worked and yes I added it to path, nice cheat, I gave you a star for it.
