### ISSUE TITLE
Cant get american version to work.

### ISSUE THREAD

**Issue by kyleg424** [naaax123/Python-CSGO-Cheat#15]
So Im new to coding and this kind of thing but I do everything like Im told and cant get it to work. I can run the china version of the cheat but it doesnt actually work in game. Below I have attached my code to what it looks like for me to try the american version out and then showing how the china version ends up working. any help
C:\Users\Owner>cd "C:\Users\Owner\Desktop\Python-CSGO-Cheat-main"

C:\Users\Owner\Desktop\Python-CSGO-Cheat-main>pip install -r requirements.txt
Requirement already satisfied: pymem in c:\users\owner\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 1)) (1.7)
Requirement already satisfied: keyboard in c:\users\owner\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 2)) (0.13.5)
Requirement already satisfied: pywin32 in c:\users\owner\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 3)) (300)
Requirement already satisfied: PyQt5 in c:\users\owner\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 4)) (5.15.3)
Requirement already satisfied: threaded in c:\users\owner\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 5)) (4.1.0)
Requirement already satisfied: requests in c:\users\owner\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 6)) (2.25.1)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in c:\users\owner\appdata\local\programs\python\python36\lib\site-packages (from PyQt5->-r requirements.txt (line 4)) (12.8.1)
Requirement already satisfied: PyQt5-Qt>=5.15 in c:\users\owner\appdata\local\programs\python\python36\lib\site-packages (from PyQt5->-r requirements.txt (line 4)) (5.15.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\owner\appdata\local\programs\python\python36\lib\site-packages (from requests->-r requirements.txt (line 6)) (1.26.3)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\owner\appdata\local\programs\python\python36\lib\site-packages (from requests->-r requirements.txt (line 6)) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\owner\appdata\local\programs\python\python36\lib\site-packages (from requests->-r requirements.txt (line 6)) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\owner\appdata\local\programs\python\python36\lib\site-packages (from requests->-r requirements.txt (line 6)) (2.10)

C:\Users\Owner\Desktop\Python-CSGO-Cheat-main>python ProjectX.py
  File "ProjectX.py", line 10
    cd 'C:\Users\Owner\Desktop\Python-CSGO-Cheat-main\requirements.txt'
                                                                      ^
SyntaxError: invalid syntax

C:\Users\Owner\Desktop\Python-CSGO-Cheat-main>python ProjectX.py
  File "ProjectX.py", line 10
    cd 'C:\Users\Owner\Desktop\Python-CSGO-Cheat-main\requirements.txt'
                                                                      ^
SyntaxError: invalid syntax

C:\Users\Owner\Desktop\Python-CSGO-Cheat-main>python chinaversion.py
f4we03qlwp5q3q45q5890wu4892h59ut)ZQ$/Z§W784zw0682732z57890Z/Z/(§$%Z=!§(%/08($12
2021-03-07 13:40:18,229 - pymem - DEBUG - Process 10236 is being debugged
2021-03-07 13:40:18,262 - pymem - DEBUG - Process 10236 is being debugged
2021-03-07 13:40:18,638 - pymem - DEBUG - Process 10236 is being debugged

**Comment by kyleg424** [comment]
Im on version 3.5 of python btw

**Comment by naaax123** [comment]
you seem to have put another line into the cheat file. Open the file with IDLE and show a screenshot pls
