### ISSUE TITLE
COOP Mission Not Working

### ISSUE THREAD

**Issue by aircodepick** [naaax123/Python-CSGO-Cheat#22]
hello can you please check and fix the issue when you play last coop mission from broken fang operation, walls and aim dosnt work just says on console round not started yet! thanks

**Comment by naaax123** [comment]
if you still need it you can just go in the code and look for the "if player and engine:" statement and diasable it

**Comment by owersite** [comment]
Please close this issue if you dont need the support from naaax anymore
