### ISSUE TITLE
Skin changer

### ISSUE THREAD

**Issue by aircodepick** [naaax123/Python-CSGO-Cheat#23]
hi can you add skin changer?

**Comment by naaax123** [comment]
external skinchangers arent really possible. I have made one you can look in the chinaversion.py file for inspiration

**Comment by owersite** [comment]
They are possible

**Comment by naaax123** [comment]
I know they are, but they are so inconsistent that it isnt really worth it. As i said if he wants to use mine he can use the one in chinaversion.py
