### ISSUE TITLE
Stopped Work, I Think Offsets Need Updated...

### ISSUE THREAD

**Issue by Konvikt** [naaax123/Python-CSGO-Cheat#24]
Believe this is the problem, I tried to fix it myself but, I ended up breaking it more when updating offsets, so might be more than that.

If you could give me a push in the right direction involving the offsets, I'd be willing to update it manually every time the game updates itself and than putting it in as a pull request for you.

**Comment by naaax123** [comment]
I use hazedumper to dump my offsets.
https://github.com/frk1/hazedumper
https://www.unknowncheats.me/forum/counterstrike-global-offensive/169351-haze-dumper-json-config-based-offset-dumper.html

**Comment by naaax123** [comment]
i can give you my config file aswell
https://pastebin.com/cTHCrZRM

**Comment by naaax123** [comment]
I updated the offsets already, but its really worth it to learn how to update them yourself

**Comment by naaax123** [comment]
If you need any help feel free to message me :)
