### ISSUE TITLE
New offsets not working.

### ISSUE THREAD

**Issue by owersite** [naaax123/Python-CSGO-Cheat#25]
New offsets not working.

**Comment by StGaLLa** [comment]
I think its a windows update who stop the script work properly and read/write csgo.exe

**Comment by naaax123** [comment]
Everythings working for me

**Comment by naaax123** [comment]
Maybe give some detail about the error message?

**Comment by owersite** [comment]
Hi naaax! Error i have is 100% with offsets, because when i launch cheat it gives me normal panel that you get by opening it but features do not work. Maybe it might not be offsets but we shall need to find it out what is it.

**Comment by naaax123** [comment]
Wait i have a windows update then ill check

**Comment by owersite** [comment]
> Wait i have a windows update then ill check

I actually have old version of windows so the new version has nothing to do with it. But i will check it up and close this issue if everything is fixed.

**Comment by adam731** [comment]
if you have discord mind adding me?
Adem#6377

**Comment by owersite** [comment]
Nope, im still pretty sure offsets are a problem

**Comment by naaax123** [comment]
Today was a cs update. Before that everything worked for me. Im updating the offsets right now and well see.

**Comment by naaax123** [comment]
Ok for me everything is 100% working. I also updated a few things in the cheat (triggerbot improvements and such). It would be very kind of you to tell me if everythings working now.

**Comment by owersite** [comment]
I will tommorow!

**Comment by owersite** [comment]
Everything works now, closing Issue!
