### ISSUE TITLE
Offsets out of date.

### ISSUE THREAD

**Issue by BinkBoinkBonk** [naaax123/Python-CSGO-Cheat#38]
New CSGO update on 4/29/2021 broke the offsets. Please use "https://raw.githubusercontent.com/frk1/hazedumper/master/csgo.json" for the offsets var in the .py files. These offsets are always updated. Please fix!

**Comment by naaax123** [comment]
1. Those offsets arent always up to date
2. 2. They dont have every offset which is needed :)
